@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package com.xiaoyue.tinkers_ingenuity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;