@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package com.xiaoyue.tinkers_ingenuity.register;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;